### ISSUE TITLE
Boundary Conditions (outlets) to Reimplement and Test

### ISSUE THREAD

**Issue by caseyfleeter** [SimVascular/svOneDSolver#22]
These outlet boundary conditions were originally available with the code, but they have not been tested so they were removed from the codebase. They could be reintegrated into the code but would need to be tested. After verifying the formulation gives correct results, **Travis** test cases would need to generated for the future.

Code re-integration: see commit 1e299f1 for the last instance with the following boundary conditions included. Note that code snippets will need to be copied from this commit and reintegrated manually, as there has been significant restructuring to the codebase that prevents a merge commit.

Regarding Travis: Run automatic test cases and compare them to analytical or numerical solutions (on Travis). Create a minimal test case for each feature of the solver and compare it to a previously computed solution. Whenever possible, use analytical solutions as a comparison.
Please modify the following lists accordingly:
- add missing features
- ~~strikethrough removed features~~
- [x] check tested features

### Reimplemented into code:
- [ ] AREA. Change in the cross sectional area.
- [ ] FLOW. Time-varying outlet flow rate.
- [ ] RESISTANCE_TIME. Time-varying resistance in model units.
- [ ] PRESSURE_WAVE
- [ ] WAVE
- [ ] LPN
- [ ] IMPEDANCE. Impedance boundary condition.
- [ ] ADMITTANCE. Admittance boundary condition.
- [ ] PULMONARY. Boundary condition using pulmonary morphometry.
- [ ] CLOSED LOOP (see issues #11 #12 #13).

Some of these require the following datatables, which also need to be tested:
- [ ] IMPEDANCE.
- [ ] RCRIMPEDANCE.
- [ ] MORPHIMPEDANCE.
- [ ] ADMITTANCE.
- [ ] RCRADMITTANCE.
- [ ] MORPHADMITTANCE.

### Analytical/numerical solution generated:
- [ ] AREA. Change in the cross sectional area.
- [ ] FLOW. Time-varying outlet flow rate.
- [ ] RESISTANCE_TIME. Time-varying resistance in model units.
- [ ] PRESSURE_WAVE
- [ ] WAVE
- [ ] LPN
- [ ] IMPEDANCE. Impedance boundary condition.
- [ ] ADMITTANCE. Admittance boundary condition.
- [ ] PULMONARY. Boundary condition using pulmonary morphometry.
- [ ] CLOSED LOOP (see issues #11 #12 #13).

Datatables:
- [ ] IMPEDANCE.
- [ ] RCRIMPEDANCE.
- [ ] MORPHIMPEDANCE.
- [ ] ADMITTANCE.
- [ ] RCRADMITTANCE.
- [ ] MORPHADMITTANCE.

### Travis test case(s) added:
- [ ] AREA. Change in the cross sectional area.
- [ ] FLOW. Time-varying outlet flow rate.
- [ ] RESISTANCE_TIME. Time-varying resistance in model units.
- [ ] PRESSURE_WAVE
- [ ] WAVE
- [ ] LPN
- [ ] IMPEDANCE. Impedance boundary condition.
- [ ] ADMITTANCE. Admittance boundary condition.
- [ ] PULMONARY. Boundary condition using pulmonary morphometry.
- [ ] CLOSED LOOP (see issues #11 #12 #13).

Datatables:
- [ ] IMPEDANCE.
- [ ] RCRIMPEDANCE.
- [ ] MORPHIMPEDANCE.
- [ ] ADMITTANCE.
- [ ] RCRADMITTANCE.
- [ ] MORPHADMITTANCE.
